In [1]:
# magic command %memit 를 사용하기 위해 필요한 라이브러리, 
import memory_profiler 
%load_ext memory_profiler
########################
# ipython_memory를 사용하여 cell별로 메모리를 계속 관찰하기 위한 라이브러리. 
import ipython_memory_usage 
import ipython_memory_usage.ipython_memory_usage as imu
%ipython_memory_usage_start

# memory watching start 
imu.start_watching_memory()

In [1] used 0.0000 MiB RAM in 0.10s, peaked 0.00 MiB above current, total RAM usage 50.80 MiB


In [1]:
import os, sys

sys.path.append('/home/dzzp/workspace/minyoung/self-supervised-nas/libs/SemiNAS/nasbench')
sys.path.append('/home/dzzp/workspace/minyoung/self-supervised-nas/libs/NAS-Bench-201/nas_201_api')
sys.path.append('/home/dzzp/workspace/minyoung/self-supervised-nas/libs/nasbench')

# Only use below functions:

### query valid acc / test acc

NASBENCH201 :
    
* arch = model_spec_201.get_modelspec(matrix= , ops= ) # if invalid, return false ; else return ModelSpec

* nasbench201.query_option(arch=arch, dataset = 'cifar10-valid', option='valid') # return random sample

* nasbench201.query_option(arch=arch, dataset = 'cifar10-valid', option='test') # return average of 3 samples

NASBENCH101 :

* arch = model_spec.get_modelspec(matrix= , ops= ) # if invalid, return false ; else return ModelSpec

* nasbench101.query_option(modelspec=arch, dataset = 'Not use in the func', option='valid') # return random sample

* nasbench101.query_option(modelspec=arch, dataset = 'cifar10-valid', option='test') # return average of 3 samples


### get budget counters

nasbench201.get_budget_counters() # return training time spent

nasbench101.get_budget_counters() # return training time spent & total epochs spent


### hash iterator & get modelspec by hash

nasbench201.hash_iterator() # possible to iterate all archs

arch = nasbench201.get_model_spec_by_hash(key)

nasbench101.hash_iterator() # possible to iterate all archs

arch = nasbench101.get_model_spec_by_hash(key)

### NAS BENCH 201

In [3]:
from nas_201_api import NASBench201API as API
import model_spec_201

dir_path = '/home/dzzp/workspace/dataset/'
nasbench201 = API(dir_path + 'NAS-Bench-201-v1_1-096897.pth')

try to create the NAS-Bench-201 api from /home/dzzp/workspace/dataset/NAS-Bench-201-v1_1-096897.pth
In [3] used 24775.7539 MiB RAM in 44.52s, peaked 940.48 MiB above current, total RAM usage 24826.63 MiB


In [32]:
for i in range(3):
    hash_val = random.choice(list(nasbench201.hash_iterator()))
    arch = nasbench201.get_model_spec_by_hash(hash_val)
    print("["+str(hash_val)+"]")
    print(arch.model_str)
    print(arch.matrix)
    print(arch.ops)
    
    val_acc = nasbench201.query_option(modelspec=arch, dataset = 'cifar10-valid', option='valid') # return random sample
    test_acc = nasbench201.query_option(modelspec=arch, dataset = 'cifar10-valid', option='test') # return average of 3 samples
    print("val_acc :", val_acc)
    print("test_acc :", test_acc)
    
    print('--------------------------------------------------------')

[ae8946f74707371c17ad123f46396630]
|skip_connect~0|+|nor_conv_1x1~0|skip_connect~1|+|skip_connect~0|nor_conv_3x3~1|nor_conv_3x3~2|
[[0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
['input', 'skip_connect', 'nor_conv_1x1', 'skip_connect', 'skip_connect', 'nor_conv_3x3', 'nor_conv_3x3', 'output']
val_acc : 82.16399998046874
test_acc : 81.85
--------------------------------------------------------
[e4a155d23839633e1af8e8f5b0430f2f]
|skip_connect~0|+|skip_connect~0|none~1|+|none~0|nor_conv_1x1~1|nor_conv_1x1~2|
[[0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]
['input', 'skip_connect', 'skip_connect', 'nor_conv_1x1', 'nor_conv_1x1', 'output']
val_acc : 73.20799999267578
test_acc : 72.41499999999999
---------------------------------------------------

### NAS BENCH 101

In [2]:
from nasbench import api
from nasbench.lib import model_spec
import random

# Use nasbench_full.tfrecord for full dataset (run download command above).
dir_path = '/home/dzzp/workspace/dataset/'
nasbench101 = api.NASBench(dir_path + 'nasbench_only108.tfrecord')

/home/dzzp/anaconda3/envs/jupyter-3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/dzzp/anaconda3/envs/jupyter-3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/dzzp/anaconda3/envs/jupyter-3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/dzzp/anaconda3/envs/jupyter-3.6

Loading dataset from file... This may take a few minutes...
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
Loaded dataset in 49 seconds


In [3]:
for i in range(3):
    hash_val = random.choice(list(nasbench101.hash_iterator()))
    arch = nasbench101.get_model_spec_by_hash(hash_val)
    print("["+str(hash_val)+"]")
    print(arch.matrix)
    print(arch.ops)
    
    val_acc = nasbench101.query_option(modelspec=arch, dataset = 'cifar10-valid', option='valid') # return random sample
    test_acc = nasbench101.query_option(modelspec=arch, dataset = 'cifar10-valid', option='test') # return average of 3 samples
    print("val_acc :", val_acc)
    print("test_acc :", test_acc)
    
    print('--------------------------------------------------------')

[243d82e1bb16243bfec43c2005e4f7d5]
[[0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 1]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
['input', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'maxpool3x3', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'output']
val_acc : 0.9038461446762085
test_acc : 0.8902911345163981
--------------------------------------------------------
[d640c07e9f942ff78d7de7a7b5d80796]
[[0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 1 0 1]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
['input', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'maxpool3x3', 'maxpool3x3', 'output']
val_acc : 0.8619791865348816
test_acc : 0.8463207880655924
--------------------------------------------------------
[a40194da2ab50e061ef7baccb839a4aa]
[[0 1 0 0 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
['input', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'maxpool3x3', 'conv1x1-bn-relu', 'conv1x